import json
import re
from openai import OpenAI
from config import OPENAI_API_KEY, OPENAI_MODEL

client = OpenAI(api_key=OPENAI_API_KEY)

def analyze_task(decoded_html: str):
    prompt = f"""
    You are a scraper parser. Extract strictly valid JSON.
    Keys: "question", "submit_url", "file_url".
    CONTENT:
    {decoded_html[:15000]}
    """
    try:
        response = client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0
        )
        content = response.choices[0].message.content.strip()
        if "```" in content:
            content = content.split("```")[1].replace("json", "")
        return json.loads(content.strip())
    except:
        return None

def solve_question(question: str, file_summary: str, page_content: str = ""):
    prompt = f"""
    You are a Data Science assistant. 
    
    QUESTION: {question}
    
    --- SCRAPED DATA (Look here!) ---
    {file_summary}
    
    --- PAGE CONTENT ---
    {page_content[:10000]}
    
    INSTRUCTIONS:
    1. **CODE SIMULATION:** If the answer is generated by JavaScript code (e.g. `await emailNumber()`), LOOK for the definition of that function in the "IMPORTED FILE" or "NESTED IMPORT" sections.
       - Read the JavaScript logic.
       - EXECUTE the logic mentally to find the result.
       - Example: If `emailNumber` returns `email.length * 10`, calculate that number.
    2. **PLACEHOLDERS:** Ignore "your secret" or "?email=".
    3. **OUTPUT:** Return strictly JSON: {{ "answer": "YOUR_CALCULATED_ANSWER" }}
    """
    
    try:
        response = client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0
        )
        content = response.choices[0].message.content.strip()
        if "```" in content:
            content = content.split("```")[1].replace("json", "")
        return json.loads(content.strip())["answer"]
    except Exception as e:
        print(f"Solve Error: {e}")
        return "Error"
